imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
      engines: ['twig']
      assets_version: 9
    default_locale: "%locale%"
    trusted_proxies: ~
    session:
      handler_id: session.handler.memcached
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
      addthis_pubid : %addthis_pubid%
      ganalytics_id : %ganalytics_id%
      fb_admins     : %fb_admins%
      plusPageUrl   : %plusPageurl%
      baseurl       : %baseurl%
      addthisevent  : %addthisevent%
      rackspace_cdn_base_url: %rackspace_cdn_base_url%
      user_session  : @user_session
      reviewService : @review
      swiftype_engine_key : %swiftype_engine_key%
      clicky_site_id: %clicky_site_id%
# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ClassCentralSiteBundle ]
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        yui_css:
             jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_js:
             jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

        lessphp:
          apply_to: "\.less$"
          formatter: "compressed"
          preserve_comments: false
    assets:
      bootstrap_css:
          inputs:
              - %kernel.root_dir%/../src/ClassCentral/SiteBundle/Resources/public/slashpixel/less/app.less
          filters:
              - lessphp
# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

services:
  search:
    class: SphinxClient
    calls:
      - [SetArrayResult,[true]]
      - [SetLimits, [0,500,1000]]
  es_client:
      class: Elasticsearch\Client
  es_courses:
      class: ClassCentral\ElasticSearchBundle\API\Courses
      arguments: [ '@es_client', '%es_index_name%']
  # Used to retrive jobs
  es_scheduler:
        class: ClassCentral\ElasticSearchBundle\API\Scheduler
        arguments: [ '@es_client', '%es_scheduler_index_name%']
  scheduler:
      class: ClassCentral\ElasticSearchBundle\Scheduler\ESScheduler
      calls:
        - [setContainer, ['@service_container'] ]
      tags:
        - { name: 'monolog.logger', channel: 'scheduler' }

  es_runner:
        class: ClassCentral\ElasticSearchBundle\Scheduler\ESRunner
        calls:
          - [setContainer, ['@service_container'] ]
  es_indexer:
      class: ClassCentral\ElasticSearchBundle\Indexer
      calls:
          - [setContainer, ['@service_container'] ]

  dom_parser:
    class: SimplehtmldomClient
  doctrine_cache:
    class: Doctrine\Common\Cache\MemcachedCache
    calls:
      - [setMemcached,[ @session.memcached ] ]
  cache:
    class: ClassCentral\SiteBundle\Services\Cache
    calls:
      - [setCache,[ @doctrine_cache ] ]
      - [setCacheKeyPrefix, [%baseurl%] ]
  mailgun:
    class: ClassCentral\SiteBundle\Services\Mailgun
    calls:
      - [setApiKey,[%mailgun_api_key%]]
      - [setDomain,[%mailgun_domain_name%]]
  newsletter:
    class: ClassCentral\SiteBundle\Services\Newsletter
    arguments: ['%mailgun_api_key%', '%mailgun_domain_name%']
  user_session:
    class: ClassCentral\SiteBundle\Services\UserSession
    arguments: ['@security.context', '@doctrine', '@session', '@service_container']
    tags:
      - { name: 'kernel.event_listener', event: 'security.interactive_login' }
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
  user_service:
    class: ClassCentral\SiteBundle\Services\User
    arguments: ['@service_container']
  verification_token:
    class: ClassCentral\SiteBundle\Services\VerificationToken
    arguments: ['@doctrine']
  filter:
      class: ClassCentral\SiteBundle\Services\Filter
      arguments: ['@service_container']
  review:
        class: ClassCentral\SiteBundle\Services\Review
        arguments: ['@service_container']
  tag:
        class: ClassCentral\SiteBundle\Services\Tag
        arguments: ['@service_container']
  # elastic serach indexer
  es_indexer:
        class: ClassCentral\ElasticSearchBundle\Indexer
        calls:
          - [setContainer, ['@service_container'] ]
  session.memcached:
    class: Memcached
    arguments:
    persistent_id: %baseurl%
    calls:
      - [ addServer, [ %session_memcached_host%, %session_memcached_port% ]]
  session.handler.memcached:
    class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
    arguments: [@session.memcached, { prefix: %baseurl%, expiretime: %session_memcached_expire% }]
