  imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

doctrine:
     orm:
         metadata_cache_driver: apc
         #result_cache_driver: apc
         query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
scheduler:
    type: stream
    path: %kernel.logs_dir%/scheduler.%kernel.environment%.log
    channels: [ scheduler ]

services:
 mailgun:
    class: ClassCentral\SiteBundle\Services\Mailgun
    calls:
      - [setApiKey,[%mailgun_api_key%]]
      - [setDomain,[%mailgun_domain_name%]]
      - [sendEmail, [true]]
