imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: info
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info
        scheduler:
            type: stream
            path: %kernel.logs_dir%/scheduler.%kernel.environment%.log
            channels: [ scheduler ]
        review_widget:
            type: stream
            path: %kernel.logs_dir%/review_widget.%kernel.environment%.log
            channels: [ review_widget ]
assetic:
    use_controller: true

services:
 mailgun:
    class: ClassCentral\SiteBundle\Services\Mailgun
    calls:
      - [setApiKey,[%mailgun_api_key%]]
      - [setDomain,[%mailgun_domain_name%]]
      - [sendEmail, [true]]
#swiftmailer:
#    delivery_address: me@example.com
