security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        ClassCentral\SiteBundle\Entity\User:
          algorithm: bcrypt
          cost: 15

    role_hierarchy:
        ROLE_ADMIN:       ROLE_STUDENT
        ROLE_SUPER_ADMIN: [ROLE_STUDENT, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_provider:
          entity:
            class:  ClassCentralSiteBundle:User
            property: email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern:    ^/
            anonymous: ~
            security: true
            form_login:
              login_path: login
              check_path: login_check
            logout:
              path: /logout
              target: /
            
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }       
#        login:
#            pattern:  ^/demo/secured/login$
#            security: false
#
#        secured_area:
#            pattern:    ^/demo/secured/
#            form_login:
#                check_path: /demo/secured/login_check
#                login_path: /demo/secured/login
#            logout:
#                path:   /demo/secured/logout
#                target: /demo/
#            #anonymous: ~
#            #http_basic:
#            #    realm: "Secured Demo Area"

#    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
