ClassCentralSiteBundle_instructor:
    resource: "@ClassCentralSiteBundle/Resources/config/routing/instructor.yml"
    prefix: /instructor
    
ClassCentralSiteBundle_stream:
    resource: "@ClassCentralSiteBundle/Resources/config/routing/stream.yml"
    prefix: /stream    
    
ClassCentralSiteBundle_course:
    resource: "@ClassCentralSiteBundle/Resources/config/routing/course.yml"
    prefix: /course  
           
ClassCentralSiteBundle_offering:
    resource: "@ClassCentralSiteBundle/Resources/config/routing/offering.yml"
    prefix: /offering       

ClassCentralSiteBundle_initiative:
    resource: "@ClassCentralSiteBundle/Resources/config/routing/initiative.yml"
    prefix: /initiative
 
ClassCentralSiteBundle_institution:
    resource: "@ClassCentralSiteBundle/Resources/config/routing/institution.yml"
    prefix: /institution

ClassCentralSiteBundle_news:
    resource: "@ClassCentralSiteBundle/Resources/config/routing/news.yml"
    prefix: /news

ClassCentralSiteBundle_language:
  resource: "@ClassCentralSiteBundle/Resources/config/routing/language.yml"
  prefix: /language

ClassCentralSiteBundle_spotlight:
  resource: "@ClassCentralSiteBundle/Resources/config/routing/spotlight.yml"
  prefix: /spotlight

ClassCentralSiteBundle_clearcache:
  pattern: /clearcache
  defaults: { _controller: ClassCentralSiteBundle:Default:clearCache}

ClassCentralSiteBundle_admin:
  pattern: /
  defaults: { _controller: ClassCentralSiteBundle:Admin:index}

ClassCentralSiteBundle_user:
  resource: "@ClassCentralSiteBundle/Resources/config/routing/user.yml"
  prefix:   /user

ClassCentralSiteBundle_newsletter:
  resource: "@ClassCentralSiteBundle/Resources/config/routing/newsletter.yml"
  prefix:   /newsletter

reviews_by_status:
  pattern: /review/status/view/{statusId}
  defaults: { _controller: ClassCentralSiteBundle:Review:reviewsByStatus }

reviews_status_update:
  pattern: /review/update/{reviewId}/{statusId}
  defaults: { _controller: ClassCentralSiteBundle:Review:reviewStatusUpdate }

substantial_reviews:
  pattern: /substantialReviews
  defaults: { _controller: ClassCentralSiteBundle:Review:substantialReviews }

ClassCentralSiteBundle_textad:
  resource: "@ClassCentralSiteBundle/Resources/config/routing/textad.yml"
  prefix:   /textad

ClassCentralSiteBundle_profile:
  resource: "@ClassCentralSiteBundle/Resources/config/routing/profile.yml"
  prefix:   /profile

ClassCentralSiteBundle_indepthreview:
  resource: "@ClassCentralSiteBundle/Resources/config/routing/indepthreview.yml"
  prefix:   /indepthreview

ClassCentralSiteBundle_interview:
  resource: "@ClassCentralSiteBundle/Resources/config/routing/interview.yml"
  prefix:   /interview

class_central_credential_credential:
  resource: "@ClassCentralCredentialBundle/Resources/config/routing/credential.yml"
  prefix:   /credential

user_suggestions_by_id:
  pattern: /suggestions/{userId}
  defaults: {_controller: ClassCentralSiteBundle:Follow:suggestionsByUser }

user_follows_by_id:
  pattern: /follows/{userId}
  defaults: {_controller: ClassCentralSiteBundle:Follow:personalizationByUser }