ClassCentral\SiteBundle\Entity\Course:
  type: entity
  repositoryClass: ClassCentral\SiteBundle\Repository\CourseRepository
  table: courses
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
      fixed: false
      nullable: false
    created:
      type: datetime
      nullable: true
    modified:
      type: datetime
      nullable: false
    shortName:
      type: string
      length: 50
      column: short_name
    url:
     type: text
    description:
      type: text
    long_description:
     type: text
     column: long_description
    syllabus:
      type: text
    videoIntro:
     type: text
     nullable: true
     column: video_intro
    length:
     type: integer
     nullable: true
    searchDesc:
     type: text
     nullable: true
     column: search_desc
    status:
      type: integer
  manyToOne:
    stream:
      targetEntity: Stream
      fetch: EAGER
      cascade: {  }      
      inversedBy: courses
      joinColumns:
        stream_id:
          referencedColumnName: id
      orphanRemoval: false  
    initiative:
      targetEntity: Initiative
      fetch: EAGER
      cascade: {}
      mappedBy: null
      inversedBy: courses
      orphanRemoval: false
      nullable: true
    language:
      targetEntity: Language
      fetch: EAGER
      cascade: {}
      mappedBy: null
      inversedBy: courses
      orphanRemoval: false
      nullable: true
  oneToMany:
    offerings:
      targetEntity: Offering
      cascade: {  }
      mappedBy: course
      inversedBy: null    
      orphanRemoval: false
    reviews:
      targetEntity: Review
      mappedBy: course
  manyToMany:    
    institutions:
      targetEntity: Institution
      inversedBy: courses      
      joinTable: 
        name: courses_institutions 
        joinColumns:
          course_id:
            referencedColumnName: id
        inverseJoinColumns:
          institution_id:
            referencedColumnName: id
      nullable: true
    instructors:
      targetEntity: Instructor
      inversedBy: courses
      joinTable:
        name: courses_instructors
        joinColumns:
          course_id:
            referencedColumnName: id
        inverseJoinColumns:
          instructor_id:
            referencedColumnName: id
      nullable: true
    tags:
      targetEntity: Tag
      inversedBy: courses
      joinTable:
        name: courses_tags
        joinColumns:
          course_id:
            referencedColumnName: id
        inverseJoinColumns:
          tag_id:
            referencedColumnName: id
lifecycleCallbacks: {  }
