ClassCentral\SiteBundle\Entity\User:
    type: entity
    table: users
    repositoryClass: ClassCentral\SiteBundle\Repository\UserRepository
    fields:
        id:
            id: true
            type: integer
            unsigndsdasded: false
            nullable: false
            generator:
                strategy: IDENTITY
        email:
            type: string
            length: 255
            fixed: false
            nullable: false
            unique: true
        name:
            type: string
            length: 255
            fixed: false
            nullable: true
        password:
            type: string
            length: 255
            fixed: false
            nullable: true
        role:
            type: string
            length: 50
            fixed: false
            nullable: false
        isActive:
            type: boolean
            nullable: true
            column: is_active
        created:
            type: datetime
            nullable: true
        modified:
            type: datetime
            nullable: false
        lastLogin:
            type: datetime
            nullable: true
            column: last_login
        isverified:
            type: boolean
            nullable: false
            column: isVerified
        signupType:
            type: integer
            unsigned: false
            nullable: true
            column: signup_type
    oneToOne:
        fb:
            targetEntity: UserFb
            mappedBy: user
    oneToMany:
        moocTrackerSearchTerms:
          targetEntity: MoocTrackerSearchTerm
          mappedBy: user
        moocTrackerCourses:
          targetEntity: MoocTrackerCourse
          mappedBy: user
        userCourses:
          targetEntity: UserCourse
          mappedBy: user
        reviews:
          targetEntity: Review
          mappedBy: user
        userPreferences:
          targetEntity: UserPreference
          mappedBy: user
    manyToMany:
      newsletters:
        targetEntity: Newsletter
        joinTable:
          name: newsletters_subscriptions
          joinColumns:
            user_id:
              referencedColumnName: id
          inverseJoinColumns:
            newsletter_id:
              referencedColumnName: id

    lifecycleCallbacks: {  }
